[package]
name = "klatt-syn-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.5.1"
itertools = { version = "0.14.0", default-features = false }
rand = "0.8.4"
